# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Josiah Parry
tagline:          'A blog for myself, and for you to read.'
description:      'Josiah Parry.'
url:              "https://josiahparry.github.io"
baseurl:           "/"


author:
  name:           'Josiah Parry'


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/josiahparry/josiahparry.github.io

gems :
  - jekyll-paginate

paginate_path: "blog/page:num"
paginate: 5
