# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "https://josiahparry.github.io"
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/josiahparry/josiahparry.github.io

gems :
  - jekyll-paginate
  - jekyll-paginate-multiple


paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num/'
    sub_dir: '/all'
  - paginate: 5
    paginate_path: '/page:num/'
    sub_dir: '/all'
