# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Josiah Parry
tagline:          'A blog for myself, and for you to read.'
description:      'Josiah Parry.'
url:              "github.com/josiahparry"
baseurl:           "/josiahparry.github.io/"


author:
  name:           'Josiah Parry'


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/josiahparry/josiahparry.github.io

gems :
  - jekyll-paginate
  - jekyll-paginate-multiple

paginate_path: "blog/page:num"
paginate: 5


paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num'
    sub_dir: '/all'
  - paginate: 5
    paginate_path: '/page:num'
    sub_dir: '/all'
