---
title: What is critical race theory, anyways?
author: ~
date: '2020-09-14'
slug: critical-race-theory
tags: [sociology, race, letters, social science, politics, theory]
draft: yes
---

_TL;DR critical race theory is a mental framework used for understanding racial inequality that focuses on power imbalances._

Trump recently suggested that all educational institutions stop teaching critical race theory and, if they fail to do so, lose funding. Like most things Trump does I was appalled. But this came from a different place. This came from a fear of educational censorship and suppression of science. 

But what the hell is critical race theory, anyways? What does it matter? 

To understand critical race theory we need to understand where it came from. Critical race theory came from the sociological critical theory. And sociological critical theory came from what is called conflict theory. And conflict theory came from—now don't lose it—Karl Marx. Let's try and grasp each theory in chronological order from when they were created to understand how each new theory came to be.

The very rough timeline looks like the below.

```{r, message=FALSE, echo=FALSE,warning=FALSE, fig.height=2}
library(nomnoml)
library(tidyverse)

p <- tibble::tribble(
  ~Year, ~Event, ~y_pos,
  1892, "Karl Marx\nHistorical Materialism", 1,
  1900, "Max Weber\nBeginnings of Conflict Theory", -1,
  1940, "The Frankfurt School\nCritical Theory", 1,
  1955, "C. Wright Mills\nModern Conflict Theory", -1,
  1987, "Kimberlé Crenshaw\nCritical Race Theory Retreat\nLegitimates CRT.", 1
) %>%
  mutate(y_pos = y_pos * .6) %>% 
  ggplot(aes(Year, y_pos, label = Event)) +
  geom_segment(aes(yend = 0, y = y_pos, xend = Year)) +
  geom_point(size = 2)  


p + geom_text(nudge_x = 2, hjust = 0, size = 3) + 
  lims(x = c(1880, 2020), y = c(1, -1)) +
  geom_segment(aes(x = 1880, y = 0, xend = 2000, yend = 0),
                  arrow = arrow(length = unit(0.2, "cm"), ends = "both")) + 
  theme_light() +
  labs(x = "", y = "") +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        panel.grid = element_blank())
```


## Historical Materialism

Okay, Karl Marx. Sure, sure, he's considered the father of communism. But he is really so much more than that. His theories have been absolutely critical to the social sciences for decades. 

Marx believed that there were two broad categories of people in a society, the proletariat and the bourgeoisie. Think of them as the workers and the business owners / managers, respectively. These two groups are always in tension with each other. Workers want better pay and better working conditions. Business owners want to save costs by paying workers less to increase their earnings at the margin (margin is jargon for each _additional_ unit of goods and services). In order to get along they each need to concede to achieve something in the middle ground. This meeting in the middle is how progress is supposedly made. 

> "Meeting in the middle" is a simplification of the German philosopher Hegel's idea of a [**dialectic**](https://www.youtube.com/watch?v=q54VyCpXDH8&ab_channel=TheSchoolofLife). A dialectic is described as "thesis, antithesis, synthesis." In normal people words a dialectic is two opposites (thesis and antithesis) creating something (synthesis).  

## Conflict Theory

Conflict theory is a bit more general than Marx's Historical Materialism. Conflict theory suggests that social structures are created from power struggles between different groups of people—not just proletariat and bourgeoisie. One group may have more authority and resources at hand and are using it to the detriment of the other group. We can think of students and teacher, homeless and housed, secular and religious, so on and so forth. 

In sociology, conflict theory is considered the antithesis (the direct opposite) of functionalism. Functionalism states that each social institution exists to serve some purpose. For example, policing serves the social function of reducing crime. Functionalists tend to think that's a good thing. Conflict theorists are likely to  disagree because they see the power imbalance between the oppressed and the oppressor _causing_ crime. These social institutions that we create tend to reinforce the status quo. 


## Critical Theory 

Okay so we're getting closer to critical race theory. To recap:

* We can trace critical race theory's origin to Marx's Historical Materialism.
* Historical Materialism says that history is a product of economic struggle between workers and business owners.
* Conflict theory generalizes Marx's theory to say that social structures are created by tension between groups based on interests, resources, and power. 

Critical theory is famously defined as 

> “an essential element in historical effort to create a world which satisfied the needs and powers of men…[and] its goal is man's emancipation from slavery” - [Horkheimer](https://www.sfu.ca/~andrewf/hork.doc)

Critical theory is essentially conflict theory but with an embedded social **critique**. It's goal is to improve the human condition by illustrating power imbalance and to improve the conditions of the oppressed. Because of this desire to improve society, critical theory is often used by activists. 

```{nomnoml, svg = TRUE, fig.height=3, echo=FALSE}
[<box>Conflict Theory |
   [Critical Theory| 
      [Critical Race Theory]
      ]]
```

The above diagram attempts to illustrate the hierarchical nature of these theories. 


## Critical Race Theory

Now making the leap from conflict theory and critical theory to critical race theory isn't all that difficult. We understand that there is historical conflict between groups of people. This conflict creates social structures and reinforces the relative power of one group to another. The created social structures perpetuate and often exacerbate inequalities. A lot of times the inequalities between groups, from a philosophical standpoint, are incongruent with our beliefs and need to be rectified or improved. 

Critical race theory, then, is the application of critical theory to the concept of race. In the American context we can understand critical race theory going all the way back to the 17th century. 

### Critical Race Theory in the United States: the really, _really_, and I cannot stress this enough, really, short version

(White) Europeans and then Americans enslaved Africans to be their source of labor. Europeans built institutions to maintain slave trading. The economy of the new world was built almost entirely on "free" labor. Social structures were modified to reinforce ownership rights between people and of people. 

Then one day on July 4th, 1776 this really important document was written which said 

> "We hold these truths to be self-evident, that all men [people] are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness." -- Declaration of Independence

But that wasn't true at all. Those words were aspirational at best. In the south, slavery was so deeply embedded that a life without it was deemed problematic enough to start a war over. When Mississippi seceded from the United States prior to the Civil War they enumerated their grievances (much like the Declaration of Independence did) to justify their departure from the US and wrote:

> "Our position is thoroughly identified with the institution of slavery—the greatest material interest of the world. Its labor supplies the product which constitutes by far the largest and most important portions of commerce of the earth." -- [A Declaration of the Immediate Causes which Induce and Justify the Secession of the State of Mississippi from the Federal Union, 1861](https://avalon.law.yale.edu/19th_century/csa_missec.asp)

It wasn't until 1865 when the 13th Amendment was ratified, 1868 for the 14th Amendment and _still_ that wasn't enough. In 1896 we had the landmark [Plessy v. Ferguson](https://www.youtube.com/watch?v=Sj54KP16Ilw&ab_channel=HISTORY) court case which paved the way for Jim Crow laws—a.k.a. American apartheid. It wasn't until 1964 until the [Civil Rights Act](https://www.history.com/topics/black-history/civil-rights-act) was passed. But the passing of laws doesn't doesn't change our thinking or our behaviors right away. We still have social structures and institutions which condition and alter our thinking. They don't disappear with the stroke of a pen.

In short, sh!t has been f*cked up in the United States for a very long time and things still aren't perfect. They're better. But they're not good. Critical race theory helps us understand how we got here, why we're still having problems, and suggests some ways that we can improve it. 

If we suppress critical race theory we're also tossing aside critical theory, conflict theory, and historical materialism. These are theories that have helped us make sense of the world for over one hundred years. If we allow this censorship we're giving way to an unjust power imbalance—the very thing these theories help us understand. If we throw away textbooks we're walking down the same path that was taken in 1930s Germany and in 1960s China. If we allow suppression of free thought we're giving way to authoritarians who don't want you to challenge injustices. 


